import '../styles/globals.css';
import Head from 'next/head';
import NextNProgress from 'nextjs-progressbar';

function MyApp({ Component, pageProps }) {
  return (<>
    <NextNProgress color="var(--f-6)"
    startPosition={0.3}
    stopDelayMs={200}
    height={3}
    showOnShallow={true}/>
    <Head>
      <title>AllMetalWelding</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.svg" type="image/svg"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </Head>
    <Component {...pageProps} />
  </>)
}

export default MyApp
